version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        volumes:
            - mongodb_data:/data/db
        ports:
            - "27017:27017"
    postgres:
        image: postgres:latest
        container_name: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tecymed_db
        ports:
            - "5432:5432"


volumes:
    mongodb_data:
    postgres_data: